name = "nexus-web"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.preview]
name = "nexus-web-preview"

[env.production]
name = "nexus-web"

[env.production.vars]
PUBLIC_API_URL = "https://nexus-api.tim-9c0.workers.dev"
